feat(react): add custom domain (#190)
Implement of https://github.com/winglang/wing/issues/6178

I also deleted `get-port` from the code, it causes a compilation error (in addition to not being used at the moment):

```
Error: require() of ES Module /Users/meir/Documents/GitHub/winglibs2/react/node_modules/get-port/index.js from /Users/meir/Documents/GitHub/winglibs2/react/utils.js not supported.
Instead change the require of index.js in /Users/meir/Documents/GitHub/winglibs2/react/utils.js to a dynamic import() which is available in all CommonJS modules.
```